site_name: Documentação de Requisitos
site_description: Documentação de requisitos de software para o projeto web
site_author: Seu Projeto

theme:
  name: material
  palette:
    - scheme: light
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - scheme: dark
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Modo claro
  
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

plugins:
  - search
  - offline

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      toc_depth: 2

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - Visão do Produto e Projeto:
      - 1 Cenário Atual do Cliente e do Negócio: doc-visao/1_cenarioAtual.md 
      - 2 Solução Proposta: doc-visao/2_solucao.md
      - 3 Intervenção Social: doc-visao/3_intervencao.md
      - 4 Estratégias de engenharia de software: doc-visao/4_estrategias.md
      - 5 Engenharia de Requisitos: doc-visao/5_requisitos.md
      - 6 Cronograma e entregas: doc-visao/6_cronograma.md
      - 7 Interação entre Equipe e Cliente: doc-visao/7_interacao.md
      - 11 Lições Aprendidas: doc-visao/11_licoes.md

  # - Atas de Reunião:
  #     - Unidade 1: atas-reuniao/ata1.md
        
  #     - Unidade 2: atas-reuniao/ata2.md
  #     - Unidade 3: atas-reuniao/ata3.md
  #     - Unidade 4: atas-reuniao/ata4.md
  # - Especificação:
  #     - Casos de Uso: especificacao/casos-uso.md
  #     - Arquitetura: especificacao/arquitetura.md
  # - Documentação:
  #     - Glossário: documentacao/glossario.md
  #     - FAQ: documentacao/faq.md
  - Entrega de vídeos: videos/entrega-videos.md
  - Referências: referencias/referencia.md
